sudo: required
services:
  - docker

before_install:
  - docker build -t mexicanopelon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mexicanopelon/react-test npm test

after_success:
  - docker build -t mexicanopelon/multi-client ./client
  - docker build -t mexicanopelon/multi-nginx ./nginx
  - docker build -t mexicanopelon/multi-server ./server
  - docker build -t mexicanopelon/multi-worker ./worker
